### PR TITLE
Feat/booking actions

### PR DESCRIPTION
**Pull request by SabiMantock**
main features:
- Implemented rocket booking Actions
- Implemented rocket cancelation Actions

### CODE REVIEW

**Review by AbdifatahYasin1 — CHANGES_REQUESTED** [review]
Hi @SabiMantock 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

Required Changes ♻️


When you clicked the button to reserve it will make another button called **reserved** as the requirements you can see. Please add that functionality.

This is what I mean. look the below screenshot.

image

**Comment by SabiMantock** [comment]
@AbdifatahYasin1 That hasn't been implemented yet, if you read the pr description you would notice it said the implementation was done for cancel and reserve. the badges would be done in the next branch

**Comment by AbdifatahYasin1** [comment]
okay thanks

**Review by AbdifatahYasin1 — APPROVED** [review]
Hello @SabiMantock 

Approved

**Pull request merged**
